pca:
  #  name: PCA
  n_components: 2

logistic:
  #  name: LogisticRegression
  penalty: l2
  n_jobs: 4

svc:
  #  name: LinearSVC
  penalty: l2


forrest:
  #  name: LinearSVC
  n_estimators: 10
  max_samples: 30
  n_jobs: 4

ensemble:
  #  name: LinearSVC
  voting: hard
